MikeSchulze/gdUnit3

addons/gdUnit3/src/core/GdUnitTools.gd, addons/gdUnit3/src/matchers/GdUnitArgumentMatchers.gd, addons/gdUnit3/src/mocking/GdUnitMockImpl.gd, addons/gdUnit3/src/spy/GdUnitSpyImpl.gd
- added custom release func to free self reference on mock and spy
=> GD-11: fix orpan instance when using mock or spy

addons/gdUnit3/src/asserts/GdAssertMessages.gd, addons/gdUnit3/src/asserts/GdAssertReports.gd, addons/gdUnit3/src/core/GdUnitObjectInteractionsTemplate.gd, addons/gdUnit3/test/mocker/GdUnitMockerTest.gd, addons/gdUnit3/test/mocker/resources/ClassWithPoolStringArrayFunc.gd, addons/gdUnit3/test/spy/GdUnitSpyTest.gd, project.godot
- The error report is extended by argument type information of interacted functions
- added test coverage of expected error reports for failing verify interactions
=> GD-22: Improve verify interactions report for mock and spy

addons/gdUnit3/src/core/GdUnitSettings.gd
- related to https://github.com/godotengine/godot/pull/46386
- needs to update Godot to version  3.2.4.
=> GD-24: Fix inital loading of GdUnit settings

addons/gdUnit3/src/core/_TestSuiteScanner.gd, addons/gdUnit3/test/core/_TestSuiteScannerTest.gd, project.godot
- renamed existing TestSuiteScanner acording to testsuite naming rule
rebuild over auto create
- added test coverage for testsuite path building
=> GD-25: Fixed automatic create test over context menu

addons/gdUnit3/src/GdUnitArrayAssert.gd, addons/gdUnit3/src/GdUnitTestSuite.gd, addons/gdUnit3/src/GdUnitTuple.gd, addons/gdUnit3/src/GdUnitValueExtractor.gd, addons/gdUnit3/src/asserts/GdUnitArrayAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitAssertImpl.gd, addons/gdUnit3/src/core/GdObjects.gd, addons/gdUnit3/src/core/GdUnitSettings.gd, addons/gdUnit3/test/asserts/GdUnitArrayAssertImplTest.gd, addons/gdUnit3/test/core/GdObjectsTest.gd, project.godot
- fix contains report by using equals to calculate 'not_expect' and 'not_found' elements
=> GD-56: Added 'extract' and 'extractv' to array_assert

addons/gdUnit3/bin/GdUnitCmdTool.gd, addons/gdUnit3/src/core/GdUnitExecutor.gd, addons/gdUnit3/src/core/report/GdUnitReport.gd, addons/gdUnit3/src/core/report/GdUnitReportCollector.gd, addons/gdUnit3/src/report/GdUnitHtmlPatterns.gd, addons/gdUnit3/src/report/GdUnitReportSummary.gd, addons/gdUnit3/src/report/GdUnitTestCaseReport.gd, addons/gdUnit3/src/report/template/css/style.css, addons/gdUnit3/test/core/GdUnitExecutorTest.gd, addons/gdUnit3/test/core/resources/testsuites/TestSuiteErrorOnTestTimeout.resource
- the errors was never counted and reported, added missing pice of code
=> GD-66: Fixed error reporting on inspector and command line tool

addons/gdUnit3/src/GdUnitTestSuite.gd, addons/gdUnit3/src/core/GdUnitExecutor.gd, addons/gdUnit3/src/core/_TestCase.gd, addons/gdUnit3/src/core/_TestSuiteScanner.gd, addons/gdUnit3/src/core/parse/GdScriptParser.gd, addons/gdUnit3/src/fuzzers/FuzzerTool.gd, addons/gdUnit3/test/core/_TestSuiteScannerTest.gd, addons/gdUnit3/test/core/parse/GdScriptParserTest.gd, addons/gdUnit3/test/core/resources/test_script_with_arguments.gd, addons/gdUnit3/test/fuzzers/GdUnitFuzzerValueInjectionTest.gd
- test cases now allow to use one or more fuzzers to generate test values
=> GD-71: Allow multiple fuzzer arguments for a test case

addons/gdUnit3/test/core/GdObjectsTest.gd
- tests now for a expected byte signature including the DIV markers for ADD or SUB
=> GD-77: Fix and improve String diff test

addons/gdUnit3/src/ui/GdUnitInspector.tscn, addons/gdUnit3/src/ui/parts/InspectorStatusBar.gd, addons/gdUnit3/src/ui/parts/InspectorStatusBar.tscn, addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit3/test/ui/parts/InspectorTreeMainPanelTest.gd, project.godot
- enables to navigate via click to next or previous failure
=> GD-83: Added failure navigation buttons to GdUnit inspector

addons/gdUnit3/src/Fuzzers.gd, addons/gdUnit3/src/core/GdObjects.gd, addons/gdUnit3/src/fuzzers/StringFuzzer.gd, addons/gdUnit3/test/core/GdObjectsTest.gd, addons/gdUnit3/test/fuzzers/StringFuzzerTest.gd, project.godot
- the stack overflow was happen on large string diffs by to many recursive calls
removed the recursive calls by loop implementation
- added String fuzzer for random string generation used to test this diff with large strings
=> GD-100: Fix stack overflow on large string diffs

addons/gdUnit3/src/core/GdObjects.gd, addons/gdUnit3/src/core/_TestSuiteScanner.gd, addons/gdUnit3/src/ui/GdUnitInspector.gd, addons/gdUnit3/test/core/_TestSuiteScannerTest.gd, addons/gdUnit3/test/core/resources/scan_testsuite_inheritance/by_class_name/BaseTest.gd, addons/gdUnit3/test/core/resources/scan_testsuite_inheritance/by_class_name/ExtendedTest.gd, addons/gdUnit3/test/core/resources/scan_testsuite_inheritance/by_class_name/ExtendsExtendedTest.gd, addons/gdUnit3/test/core/resources/scan_testsuite_inheritance/by_class_path/BaseTest.gd, addons/gdUnit3/test/core/resources/scan_testsuite_inheritance/by_class_path/ExtendedTest.gd, addons/gdUnit3/test/core/resources/scan_testsuite_inheritance/by_class_path/ExtendsExtendedTest.gd, project.godot
- added resource_path check on is extends from a test suite
=> GD-131: Allow to extend an existing test suite by resource_path

addons/gdUnit3/src/core/event/GdUnitEvent.gd, addons/gdUnit3/src/ui/GdUnitConsole.gd, addons/gdUnit3/src/ui/GdUnitConsole.tscn
- improved a bit the test reports on the GdUnit console by using monospaced font and reformatting text and colors
=> GD-183: Use monospaced font on GdUnit console to prints formatted

addons/gdUnit3/src/asserts/GdAssertMessages.gd, addons/gdUnit3/src/asserts/GdUnitAssertImpl.gd, addons/gdUnit3/src/core/report/GdUnitReport.gd, addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit3/src/ui/parts/InspectorTreePanel.tscn, addons/gdUnit3/src/ui/parts/RichTextEffectBackground.gd, addons/gdUnit3/src/ui/parts/RichTextLabelExt.gd, project.godot
- Use of background colors to visualize differences in unexpected and missing characters
- Redesign of the inspector by adding a frame between the tree and the report panel
- Recalculation of the minimum text width in the report panel to fix problems with the scroll bar
=> GD-185: Improved visualization of the error report.

addons/gdUnit3/src/asserts/GdAssertMessages.gd, addons/gdUnit3/src/asserts/GdUnitArrayAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitBoolAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitDictionaryAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitFloatAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitIntAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitStringAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitVector2AssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitVector3AssertImpl.gd, addons/gdUnit3/test/asserts/GdUnitArrayAssertImplTest.gd, addons/gdUnit3/test/asserts/GdUnitBoolAssertImplTest.gd, addons/gdUnit3/test/asserts/GdUnitDictionaryAssertImplTest.gd, addons/gdUnit3/test/asserts/GdUnitFloatAssertImplTest.gd, addons/gdUnit3/test/asserts/GdUnitIntAssertImplTest.gd, addons/gdUnit3/test/asserts/GdUnitObjectAssertImplTest.gd, addons/gdUnit3/test/asserts/GdUnitStringAssertImplTest.gd, addons/gdUnit3/test/asserts/GdUnitVector2AssertImplTest.gd, addons/gdUnit3/test/asserts/GdUnitVector3AssertImplTest.gd
- fix assert_bool
- fix assert_string
- fix assert_int
- fix assert_float
- fix assert_array
- fix assert_object
- fix assert_vector2
- fix assert_vector3
=> GD-193: Handle null values for all asserts to prevent GdUnit to stop working

addons/gdUnit3/plugin.cfg, addons/gdUnit3/src/core/GdUnitExecutor.gd, addons/gdUnit3/test/GdUnitTestCaseTimingTest.gd, addons/gdUnit3/test/core/GdUnitExecutorTest.gd, addons/gdUnit3/test/core/resources/testsuites/GdUnitFuzzerTest.resource, addons/gdUnit3/test/fuzzers/GdUnitFuzzerValueInjectionTest.gd
- before_test and after_test were called only once, but must be called for each test case iteration
=> GD-195: Call before_test and after_test for parameterized tests for each iteration.

addons/gdUnit3/src/core/_TestSuiteScanner.gd, addons/gdUnit3/src/core/parse/GdScriptParser.gd, addons/gdUnit3/test/core/_TestSuiteScannerTest.gd, addons/gdUnit3/test/core/parse/GdScriptParserTest.gd, addons/gdUnit3/test/core/resources/test_script_with_arguments.gd, addons/gdUnit3/test/fuzzers/GdUnitFuzzerValueInjectionTest.gd
- a test can have many arguments and it should be possible to format the test function in multiple lines
=> GD-197: Add support for multiline formatted test function arguments

addons/gdUnit3/src/GdUnitSceneRunner.gd, addons/gdUnit3/src/GdUnitTestSuite.gd, addons/gdUnit3/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit3/src/core/GdUnitTools.gd, addons/gdUnit3/test/core/GdUnitSceneRunnerTest.gd, addons/gdUnit3/test/core/GdUnitToolsTest.gd, addons/gdUnit3/test/core/resources/scenes/simple_scene.gd, addons/gdUnit3/test/core/resources/scenes/simple_scene.tscn, addons/gdUnit3/test/scenes/NetworkSceneTest.gd, addons/gdUnit3/test/ui/templates/TestSuiteTemplateTest.gd
- scene runner now supports additional to load a scene by resource path
- loaded scene will be freed by runner on release
- fix/cleanup how used the runner in test
=> GD-232: Allow to load scene runner by scene resource path

addons/gdUnit3/src/ui/parts/InspectorToolBar.gd
redirect now to new documentation page
=> GD-239: Update documentation link on inspector

addons/gdUnit3/src/ui/parts/InspectorProgressBar.gd
=> Fix EditorPlugin object leak in InspectorProgressBad.gd

addons/gdUnit3/src/asserts/GdAssertMessages.gd, addons/gdUnit3/src/asserts/GdUnitArrayAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitDictionaryAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitFuncAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitSignalAssertImpl.gd, addons/gdUnit3/src/asserts/GdUnitStringAssertImpl.gd, addons/gdUnit3/src/core/GdDiffTool.gd, addons/gdUnit3/src/core/GdObjects.gd, addons/gdUnit3/src/core/GdUnitTools.gd, addons/gdUnit3/src/ui/parts/InspectorTreePanel.tscn, addons/gdUnit3/test/asserts/GdUnitArrayAssertImplTest.gd, addons/gdUnit3/test/core/GdDiffToolTest.gd, addons/gdUnit3/test/core/GdObjectsTest.gd, project.godot
- show only the invalid current values colored in red
- show unexpected values in an indexed table
=> GD-303: Improve array assert to show better report
