- addons/gdUnit3/src/GdUnitMock.gd
- addons/gdUnit3/src/GdUnitTestSuite.gd
- addons/gdUnit3/src/mocking/GdUnitMockImpl.gd
- addons/gdUnit3/src/spy/GdUnitSpyImpl.gd
- addons/gdUnit3/test/mocker/GdUnitMockerTest.gd
- addons/gdUnit3/test/spy/GdUnitSpyTest.gd
- reset(<spy|mock>) allows now to reset the actual counted function calls for continues testing wiht the same spy or mock
> GD-15: Added reset for mock and spy

- addons/gdUnit3/src/GdUnitTestSuite.gd
- addons/gdUnit3/src/asserts/GdAssertReports.gd
- addons/gdUnit3/src/asserts/GdUnitAssertImpl.gd
- addons/gdUnit3/src/core/GdUnitClassDoubler.gd
- addons/gdUnit3/src/core/GdUnitObjectInteractions.gd
- addons/gdUnit3/src/core/GdUnitObjectInteractionsTemplate.gd
- addons/gdUnit3/src/mocking/GdUnitMock.gd
- addons/gdUnit3/src/mocking/GdUnitMockBuilder.gd
- addons/gdUnit3/src/mocking/GdUnitMockImpl.gd
- addons/gdUnit3/src/spy/GdUnitSpyBuilder.gd
- addons/gdUnit3/src/spy/GdUnitSpyImpl.gd
- addons/gdUnit3/test/mocker/GdUnitMockerTest.gd
- addons/gdUnit3/test/spy/GdUnitSpyTest.gd
- project.godot
- verify_no_interactions returns now the used GdUnitAssert instance for better test coverage
- added test coverage for verify_no_interactions
- fix small bug in asssertion expect to fail, fix error line reporting
- improve the error message for verify_no_interactions, now lists unexpected interactions
> GD-20: Refactore verify_no_interactions to return GdUnitAssert:

- .gitignore
- addons/gdUnit3/src/core/GdUnitRunner.gd
- addons/gdUnit3/src/core/GdUnitRunnerConfig.gd
- addons/gdUnit3/src/network/GdUnitServer.gd
- addons/gdUnit3/src/network/Network.gd
- addons/gdUnit3/src/ui/GdUnitInspector.gd
- addons/gdUnit3/test/core/GdUnitRunnerConfigTest.gd
- project.godot
- comple rewrite GdUnitRunnerConfig and add test coverage
- the runner config is now stored in the project directory
- test server uses now retry to start to find next free port
> GD-28: Add support to run GdUnit in multipe Godot instances concurent

- addons/gdUnit3/src/core/_TestSuiteScanner.gd
- addons/gdUnit3/test/core/TestSuiteScannerTest.gd
- added '-> void:' to generated tests to be conform with static typed GDScript
> GD-26: Generate static typed GDScript tests

- addons/gdUnit3/src/asserts/GdUnitAssertImpl.gd
- root cause was, on debug mode no stack trace is available and the 'get_stack()' will rsturn an empty array
> GD-27: Fix 'Run Tests' without debug mode shows no errors

- addons/gdUnit3/src/core/GdUnitClassDoubler.gd
- addons/gdUnit3/src/mocking/GdUnitMockBuilder.gd
- addons/gdUnit3/src/spy/GdUnitSpyBuilder.gd
- addons/gdUnit3/test/mocker/GdUnitMockerTest.gd
- addons/gdUnit3/test/mocker/resources/snake_case.gd
- addons/gdUnit3/test/mocker/resources/snake_case_class_name.gd
- addons/gdUnit3/test/spy/GdUnitSpyTest.gd
- project.godot
- clazz double was run into issues when the source class name is snake case.
the doubled class was extending by name where is not supports snake case format
to fix use the full class path to extend
> GD-32: Fix mock and spy on class with snake case names.

- .gitattributes
By excluding files outside the `/addons` directory the AssetLib download only contains necessary files making users happy.
You can check ie with https://github.com/bitwes/Gut/blob/master/.gitattributes and what its AssetLib result is.
> Make AssetLib users happy.

- addons/gdUnit3/src/ui/GdUnitInspector.gd
- use now editor context menu to save all files opend in the editor
for now we save ALL files, the Godot API provided no function to check if a script modified in the editor
> GD-44: Fix save modified files before run test

- addons/gdUnit3/src/core/parse/GdScriptParser.gd
- addons/gdUnit3/test/core/parse/GdScriptParserTest.gd
- addons/gdUnit3/test/mocker/GdUnitMockerTest.gd
- addons/gdUnit3/test/mocker/resources/ClassWithDefaultBuildIntTypes.gd
- addons/gdUnit3/test/spy/GdUnitSpyTest.gd
- project.godot
- parsing function arguments was not handling build in types
the value was splitted up by using 'tokenize_value' from 'Color.red' into 'Color' and 'red'
fixes by parsiong the full value until next arg or enf of function
- the parsed arg name was handled by ValueToken as typed value, this was resulting in wrong type
'aabb' was interpreted as an TYPE_INT (hex)
so i introduced to use the plain value instead to fix
> GD-48: Fixed mock and spy fail on class with default build in types

- addons/gdUnit3/src/network/Network.gd
- solved disconnectings during a debug session
> GD-01: Set test client peer timeout to 5min to prevent disconnect for long running testcases.

- addons/gdUnit3/src/GdUnitTestSuite.gd
- addons/gdUnit3/src/asserts/GdUnitArrayAssertImpl.gd
- addons/gdUnit3/src/asserts/GdUnitAssertImpl.gd
- addons/gdUnit3/src/core/GdObjects.gd
- addons/gdUnit3/src/core/GdUnitExecutor.gd
- addons/gdUnit3/src/core/GdUnitRunner.gd
- addons/gdUnit3/src/core/GdUnitTools.gd
- addons/gdUnit3/src/core/_TestCase.gd
- addons/gdUnit3/src/core/_TestSuiteScanner.gd
- addons/gdUnit3/src/ui/parts/InspectorStatusBar.gd
- addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd
- addons/gdUnit3/test/GdUnitTestCaseTimeoutTest.gd
- addons/gdUnit3/test/asserts/GdUnitArrayAssertImplTest.gd
- addons/gdUnit3/test/core/GdObjectsTest.gd
- addons/gdUnit3/test/core/GdUnitToolsTest.gd
- addons/gdUnit3/test/core/_TestSuiteScannerTest.gd
- addons/gdUnit3/test/core/parse/GdScriptParserTest.gd
- addons/gdUnit3/test/core/resources/test_script_with_arguments.gd
- the new argument 'timeout' allows to specify a custom timeout value for each test in ms
if a test runs longer than the timeout is configured the test will be interupped and fail with an error
- default test timeout is set to 5min
> GD-55: Added timeout argument to test case

- addons/gdUnit3/plugin.gd
- addons/gdUnit3/src/core/GdUnitMemoryPool.gd
- addons/gdUnit3/src/core/GdUnitSettings.gd
- addons/gdUnit3/src/core/_TestCase.gd
- addons/gdUnit3/src/network/Network.gd
- addons/gdUnit3/test/core/GdUnitExecutorTest.gd
- addons/gdUnit3/test/core/GdUnitMemoryPoolTest.gd
- addons/gdUnit3/test/core/_TestSuiteScannerTest.gd
- project.godot
- added new project settings
-- 'gdunit3/report/verbose_orphans'
allowes to control orphan reporting
-- 'gdunit3/settings/server_connection_timeout_minutes'
allows to configure connection timeout of GdUnit report server
-- 'gdunit3/settings/test_timeout_seconds'
allows to configure the default test timeout in seconds
> GD-62: Added project settings to disable/enable reporting detected orphans

- .github/workflows/selftest-3.2.x.yml
- addons/gdUnit3/src/cmd/CmdCommandHandler.gd
- addons/gdUnit3/src/core/GdUnitExecutor.gd
- addons/gdUnit3/src/core/GdUnitTools.gd
- addons/gdUnit3/src/core/report/GdUnitReportCollector.gd
- addons/gdUnit3/test/asserts/GdUnitVector3AssertImplTest.gd
- addons/gdUnit3/test/cmd/CmdCommandHandlerTest.gd
- With Godot 3.2.x array does not support 'append_array', which was introduced with Godot 3.3
Compensation function added to GdUnitTools.append_array to be compatible
- vector3 tests was failing base on to high resolution, minimized by one decimal place
- CommandHandle was broken by using FuncRef:get_function() where not exists in Godot 3.2.x
fixes by disabled the enhanced command register validation
> GD-76: Fix broken compatibility to Godot 3.2.x

- addons/gdUnit3/plugin.gd
- addons/gdUnit3/src/core/GdUnitSingleton.gd
- addons/gdUnit3/src/network/GdUnitTcpClient.gd
- addons/gdUnit3/src/network/GdUnitTcpServer.gd
- addons/gdUnit3/src/network/rpc/RPC.gd
- addons/gdUnit3/src/ui/parts/InspectorStatusBar.gd
- addons/gdUnit3/src/ui/parts/InspectorToolBar.gd
- addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd
- removed usage of `EditorPlugin.new()` and using already stored meta info
- fix very strange bug on RPC.deserialize, the use of type save function declaration results in a orpan node
> GD-102: Fix orphan nodes detected during export via command line.

- addons/gdUnit3/src/core/GdUnitExecutor.gd
- addons/gdUnit3/test/core/GdUnitExecutorTest.gd
- addons/gdUnit3/test/core/resources/testsuites/TestSuiteFailAddChildStageBefore.resource
- adding custom nodes on the test suite `before()` was break the test case execution
solved by adding a typeof check when iteration over the childs to only execute on test case
> GD-106: Fix using add_child on before() in test suites do not break the API

- addons/gdUnit3/src/core/event/GdUnitEvent.gd
- addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd
- addons/gdUnit3/test/ui/parts/InspectorTreeMainPanelTest.gd
Adds a counter to the test suites which displays the success / total ratio for that test suite. Updates as each test case finishes.
Unit tests for the feature are included.
Also fixed a typo with "statisics" v.s. "statistics"
> Added "(successes/total)" counter to test suite display.

- addons/gdUnit3/src/network/GdSerde.gd
- addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd
- addons/gdUnit3/test/GdUnitTestResourceLoader.gd
- addons/gdUnit3/test/ui/parts/InspectorTreeMainPanelTest.gd
- addons/gdUnit3/test/ui/parts/resources/bar/ExampleTestSuiteA.resource
- addons/gdUnit3/test/ui/parts/resources/foo/ExampleTestSuiteA.resource
- addons/gdUnit3/test/ui/parts/resources/foo/ExampleTestSuiteB.resource
- addons/gdUnit3/test/ui/parts/resources/foo/ExampleTestSuiteC.resource
- project.godot
- The GdUnitInspector was not able to correctly address events for test suites with the same name.
- Fixed it by using the resource_path instead of suite name to adress the correct item in the inspector
> GD-117: Fixed GdUnitInspector event handling for test-suites with same name

- addons/gdUnit3/src/GdUnitArrayAssert.gd
- addons/gdUnit3/src/asserts/GdAssertMessages.gd
- addons/gdUnit3/src/asserts/GdUnitArrayAssertImpl.gd
- addons/gdUnit3/src/core/GdObjects.gd
- addons/gdUnit3/test/asserts/GdUnitArrayAssertImplTest.gd
- addons/gdUnit3/test/asserts/GdUnitArrayAssertImpl_PoolByteArrayTest.gd
- addons/gdUnit3/test/update/GdUnitUpdateTest.gd
- added `contains_exactly_in_any_order` to alow compare arrays unordered
- improve the error messages
- fix random failing `GdUnitUpdateTest:test_extract_package` by using the new function
> GD-122: Added `contains_exactly_in_any_order` to `GdUnitArrayAssert`

- addons/gdUnit3/src/core/GdUnitSceneRunner.gd
- gdUnit3-examples/RoomDemo3D/test/rooms/RoomWithDoorTest.gd
- with `set_time_factor(<time_shift>)` we can now control the time factor
- refactor RoomWithDoorTest example to use the new time factore functionallity to speed up this test suite (13s to 3s)
> GD-120: Added time factor functionallity to scene runner to speedup scene testing

- addons/gdUnit3/src/update/GdUnitUpdate.gd
- addons/gdUnit3/test/update/GdUnitUpdateTest.gd
- The unpack by tool `tar` was failing if multible tar version installed.
Fixed by lookup and use the full path for windows provided tar tool
> GD-113: GdUnitUpdate now using the windows provided tar to unpack the update-zip

- addons/gdUnit3/src/GdUnitTestSuite.gd
- addons/gdUnit3/src/GdUnitValueExtractor.gd
- addons/gdUnit3/src/asserts/GdUnitArrayAssertImpl.gd
- addons/gdUnit3/src/extractors/GdUnitFuncValueExtractor.gd
- addons/gdUnit3/test/asserts/GdUnitArrayAssertImplTest.gd
- addons/gdUnit3/test/extractors/GdUnitFuncValueExtractorTest.gd
- project.godot
- moved implementation from `GdUnitValueExtractor` to `GdUnitFuncValueExtractor` and convert to an interface
- added function name chaining on `extr` func
- added function name chaining on ArrayAssert:extract and extractv
> GD-133: Improve the value extractor `extr` to support function name chaining

- addons/gdUnit3/src/core/GdUnitSettings.gd
- addons/gdUnit3/src/core/_TestSuiteScanner.gd
- addons/gdUnit3/src/ui/GdUnitToolsDialog.tscn
- addons/gdUnit3/src/ui/templates/TestSuiteTemplate.gd
- addons/gdUnit3/src/ui/templates/TestSuiteTemplate.tscn
- addons/gdUnit3/test/ui/templates/TestSuiteTemplateTest.gd
- project.godot
- extend the GdUnit tools dialog by adding template tab
- the test suite template can now modify, save, restore
> GD-142: Allow to edit the test suite template

- addons/gdUnit3/plugin.cfg
- addons/gdUnit3/plugin.gd
- Godot was crashing on MacOS because of invalid removing `_update_tool`
> GD-144: Fix Godot crash on MacOS when closing

- addons/gdUnit3/src/core/GdUnitSceneRunner.gd
Currently, the runner only allows to simulate until the scene object itself emits a signal. Very often however we have objects in the scene that we try to simulate and the scene itself is just a test harness. With this new function the scene runner can now simulate the scene until any object that is given to the function will emit a specific signal.
> `SceneRunner`, Simulate scene until a specific object emits a signal

- addons/gdUnit3/bin/GdUnitCmdTool.gd
- `run cmdtool -conf` -> loads by default the GdUnitRunner.cfg
- `run cmdtool -conf myconf.cfg` -> loads the given test configuration
> GD-161: Add `-conf` option to Command Line Tool to load latest test execution configuration

- addons/gdUnit3/bin/GdUnitCmdTool.gd
- addons/gdUnit3/src/core/GdUnitExecutor.gd
- addons/gdUnit3/src/ui/GdUnitInspector.gd
- the extra yield for each fuzzer iteration results in very long test run time and was not needed.
> GD-162: Remove extra yielding between fuzzer iterations

- addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd
- the popup was simply wrong used by `show` instead of using `popup`
> GD-181: Hide test inspector context menu when click somewhere.

- addons/gdUnit3/src/ui/GdUnitConsole.gd
- addons/gdUnit3/src/ui/GdUnitConsole.tscn
- addons/gdUnit3/src/ui/parts/RichTextEffectBackground.gd
- addons/gdUnit3/src/ui/parts/RichTextLabelExt.gd
- addons/gdUnit3/test/ui/parts/RichTextEffectBackgroundTest.gd
- project.godot
- the GdUnit console used indent report lines where was not correct shown (diff colors was incorect placed)  
- speedup rendering by using a precalculated character position cache
> GD-185: Fix RichTextEffectBackground diff visualisation for indent lines

- addons/gdUnit3/plugin.cfg
- addons/gdUnit3/src/asserts/GdAssertMessages.gd
- addons/gdUnit3/src/asserts/GdUnitResultAssertImpl.gd
- addons/gdUnit3/test/asserts/GdUnitResultAssertImplTest.gd
- the `assert_result` was not handling null values as result and runs into invalid calls and stops gdunit working
> GD-191: Handle null values on `assert_result`

- addons/gdUnit3/plugin.gd
- addons/gdUnit3/src/update/GdUnitUpdate.gd
- adding the dialoge to the root node results in showing the ui elements by project theme
but we want to have the current editor theme
- hide first the update dialoge after succes update before reenable the plugin to prevent resource loading clashes
- Replace the update information before deleting the old resources to avoid errors caused by missing resources.
> GD-202: Add update popup dialoge to plugin by using `add_control_to_container` to have the editor theme

- addons/gdUnit3/test/fuzzers/FuzzerToolTest.gd
- addons/gdUnit3/test/fuzzers/GdUnitFuzzerValueInjectionTest.gd
- addons/gdUnit3/test/fuzzers/TestExternalFuzzer.gd
- project.godot
- improved test coverage to create fuzzers as test arguments
- Godot has problems with nested classes when using as custom scrips
- build a script from a source and reload results in a invalid function callback type
see FuzzerToolTest:test_create_nested_fuzzer_do_fail
> GD-207: Improve fuzzer injection tests

- addons/gdUnit3/src/ui/Fonts.gd
- addons/gdUnit3/src/ui/GdUnitConsole.tscn
- addons/gdUnit3/src/ui/parts/RichTextEffectBackground.gd
- addons/gdUnit3/src/ui/parts/RichTextLabelExt.gd
- addons/gdUnit3/test/ui/parts/RichTextEffectBackgroundTest.gd
- The failure highlighting was placed incorrectly when the text is warped.
Now the minimum text field length is set to the maximum text length to avoid line breaks.
> GD-215: Fix failure highlighting on GdUnit Console

- addons/gdUnit3/src/ui/GdUnitToolsDialog.gd
- addons/gdUnit3/src/ui/GdUnitToolsDialog.tscn
- the property values was not fully displayed if using alignment RIGHT, swichted to CENTER
- added scroll container fit the conten an show scrollbar if need
> GD-214: Fix GdUnit configurations dialog to show all properties

- .github/workflows/selftest-3.3.x-mono.yml
- .github/workflows/selftest-3.3.x.yml
- .github/workflows/selftest-3.4.x.yml
- addons/gdUnit3/bin/GdUnitCmdTool.gd
- addons/gdUnit3/src/report/GdUnitTestCaseReport.gd
- failure reports now printed out for failing tests
- reduce font loading by using a single instance of RTL
> GD-231: Print failure report on comand line tool execution

- addons/gdUnit3/src/core/GdObjects.gd
- addons/gdUnit3/test/asserts/GdUnitArrayAssertImplTest.gd
- a test case was stucking on `assert_array().contains_exactly()` when the elements to compare has a circular dependencies
e.g. child/parent relation
The root couse was the deep_check comparing of two object by using `var2str`.
Replace it by `inst2dict` for script based object which is able to handle complex objects.
> GD-244: Fix stucking test execution when using `assert_array`

- addons/gdUnit3/src/core/parse/GdScriptParser.gd
- addons/gdUnit3/test/core/parse/GdScriptParserTest.gd
- addons/gdUnit3/test/mocker/GdUnitMockerTest.gd
- The parser did not stop parsing at the function head end.
Fixed by stopping parsing when the function head end is reached.
> GD-248: Mock was failing for a class that directly calls an inheritance method

- addons/gdUnit3/src/monitor/GodotGdErrorMonitor.gd
- the error scanner was stop parsing log on first empty line and results in no error detected
solved by scan until eof
> GD-260: GdUnit3 doesn't fail on script errors during test run

- .github/workflows/selftest-3.3.x-mono.yml
- addons/gdUnit3/src/core/GdObjects.gd
- addons/gdUnit3/src/core/parse/GdScriptParser.gd
- addons/gdUnit3/src/mocking/GdUnitMockBuilder.gd
- addons/gdUnit3/src/spy/GdUnitSpyBuilder.gd
- addons/gdUnit3/test/mocker/GdUnitMockerTest.gd
- addons/gdUnit3/test/mocker/GodotClassNameFuzzer.gd
- addons/gdUnit3/test/mocker/resources/ClassWithCustomClassName.gd
- addons/gdUnit3/test/mocker/resources/GD-256/world.gd
- addons/gdUnit3/test/mocking/GdUnitMockBuilderTest.gd
- addons/gdUnit3/test/spy/GdUnitSpyTest.gd
- project.godot
- using now the `class_name` of source class to build the mock class name instead grabing from resource path
We do this because the `class_name` can be differ from file name.
- if no `class_name` defined we fallback to the grap class name from file
- cleanup unused arguments on mock and spy builder
- replace nuget restore by dotnet restore to solve flaky build errors
> GD-256: Build a mock inherits with the wrong class if the filename matches an existing class

- addons/gdUnit3/src/core/GdUnitTestSuiteBuilder.cs
- addons/gdUnit3/test/core/GdUnitTestSuiteBuilderTest.cs
- addons/gdUnit3/test/core/resources/testsuites/mono/noSpace/TestSuiteWithoutNamespace.cs
- The recognition of an test suite was interrupted if no namespace was defined.
> GD-262: Fixed parsing of test suites without namespace

- addons/gdUnit3/src/core/_TestSuiteScanner.gd
- addons/gdUnit3/test/core/TestSuiteScannerTest.gd
- project.godot
- a small pice of hard coded path check was stopping the test scanning.
removed it do alow scanning each folder
- added test coverage for test folder generation
> GD-263: Tests was not found when changing the `test root folder` property

- addons/gdUnit3/src/GdUnitAwaiter.gd
- addons/gdUnit3/src/core/GdUnitSignalAwaiter.gd
- addons/gdUnit3/test/core/GdUnitSignalAwaiterTest.gd
- project.godot
- the emited signal value was not returned ans is now transport to the caller
> GD-280: `await_signal_on` do now return the emited value

- addons/gdUnit3/src/asserts/GdUnitAssertImpl.gd
- addons/gdUnit3/src/core/parse/GdScriptParser.gd
- addons/gdUnit3/test/core/parse/GdScriptParserTest.gd
- addons/gdUnit3/test/mocker/resources/ClassWithCustomFormattings.gd
- addons/gdUnit3/test/spy/GdUnitSpyTest.gd
- spy was failing to parse the function signature for custom formatted functions
- scans now until end of function to collect the complete function signature
- fix error line detection for `verify_no_interactions` and `verify_no_more_interactions`
> GD-291: Spy fails for class with custom formatted function signature

- .github/actions/install-godot/action.yml
- .github/actions/publish-test-report/action.yml
- .github/actions/unit-test/action.yml
- .github/actions/upload-test-report/action.yml
- .github/workflows/ci-pr.yml
- addons/gdUnit3/bin/GdUnitCmdTool.gd
- addons/gdUnit3/scan_project.gd
- addons/gdUnit3/scan_project.tscn
- addons/gdUnit3/src/cmd/CmdOptions.gd
- addons/gdUnit3/src/ui/parts/InspectorToolBar.gd
- addons/gdUnit3/src/update/GdUnitUpdate.gd
- addons/gdUnit3/test/cmd/CmdOptionsTest.gd
- default_env.tres
- runtest.sh
- create ci-pr workflow
- using a matrix to iterate over supported Godot versions
- split existing jobs into separate actions
> GD-295: Add `CI-PR` workflow to run on pull requests

- addons/gdUnit3/plugin.cfg
- addons/gdUnit3/src/network/GdUnitServerConstants.gd
- addons/gdUnit3/src/network/GdUnitTcpClient.gd
- addons/gdUnit3/src/network/GdUnitTcpServer.gd
- addons/gdUnit3/test/asserts/GdUnitStringAssertImplTest.gd
- project.godot
- the split of server data packages was broken when data contains a extra pipe character
use now an dedicated delemiter instead
- bump to version 2.2.5
> GD-305: Fix client/server request json parsing

- addons/gdUnit3/bin/GdUnitCmdTool.gd
- Fix misspelled 'testsiute' to 'testsuite'.
> Fix Typo in GdUnitCmdTool.gd

- addons/gdUnit3/src/GdUnitSignalAssert.gd
- addons/gdUnit3/src/asserts/GdAssertReports.gd
- addons/gdUnit3/src/asserts/GdUnitAssertImpl.gd
- addons/gdUnit3/src/asserts/GdUnitSignalAssertImpl.gd
- addons/gdUnit3/test/asserts/GdUnitSignalAssertImplTest.gd
- assert_signal was not collection all emitted signal when using multiple times on the same emitter
- refacore the signal collector to use an singleton to collect all signals over the emitter live time
> GD-318: rework on assert_signal to collect all emitted signals

- addons/gdUnit3/src/report/XmlElement.gd
- addons/gdUnit3/test/report/XmlElementTest.gd
- a failure message was writen plain in the XML and resulting in a invalid XML
- fixed by enclose the message in a CDATA block
> GD-322: Encloses the error message when writing a JUnit XML report in a CDATA block

- addons/gdUnit3/src/core/GdUnitExecutor.gd
- addons/gdUnit3/src/core/_TestCase.gd
- addons/gdUnit3/src/network/rpc/dtos/GdUnitTestCaseDto.gd
- addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd
- addons/gdUnit3/test/GdUnitTestResourceLoader.gd
- addons/gdUnit3/test/GdUnitTestResourceLoaderTest.gd
- addons/gdUnit3/test/core/GdUnitExecutorTest.gd
- addons/gdUnit3/test/core/TestSuiteScannerTest.gd
- addons/gdUnit3/test/core/resources/testsuites/TestSuiteInvalidParameterizedTests.resource
- addons/gdUnit3/test/core/resources/testsuites/TestSuiteParameterizedTests.resource
- project.godot
- moved the test case name building from UI to backend to be compatible with the c# test case name building
- fix GdUnitTestResourceLoader.gd bug on loading resource containing inner classes
- add executor test for parameterized tests
> Introduce 'test_case_names()' on test case to build the test case names from given parameter set

- addons/gdUnit3/src/core/GdUnitRunnerConfig.gd
- the error was shown since i switch to JSON format for config file on the c# explorer
- to fix we now write/read consistent in JSON format for Godot and VSC plugin
> GD-327: Fix 'Unicode error: invalid skip' on plugin startup

- addons/gdUnit3/src/core/GdUnitExecutor.gd
- addons/gdUnit3/src/core/GdUnitRunner.gd
- addons/gdUnit3/src/core/GdUnitRunnerConfig.gd
- addons/gdUnit3/src/core/_TestCase.gd
- addons/gdUnit3/src/ui/GdUnitInspector.gd
- addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd
By default, you can execute only one selected test or test suite. For parameterized tests, the inspector is populated with all parameterized tests when the test is executed. If a test fails, you have to re-run the entire test case, but it would be nice if you could select one of the parameterized test runs and re-run it as a single case.
Implemented to run a selected parameterized test case via the inspector context menu.
> GD-337: Allow to run a single parameterized test from the inspector

- addons/gdUnit3/src/core/parse/GdScriptParser.gd
- addons/gdUnit3/test/core/parse/GdScriptParserTest.gd
Loading of a test suite with an parameterized test and a huge parameter set was resulting in extrem long loading time
Simplifyed the function descriptor parsing to speedup loading time.
> GD-336: Improve test suite parsing for large function descriptors

- addons/gdUnit3/src/core/parse/GdScriptParser.gd
- addons/gdUnit3/test/core/ParameterizedTestCaseTest.gd
- addons/gdUnit3/test/core/parse/GdScriptParserTest.gd
Using dictionary on a parameterized was end up into a runtime error.
Fix the script parser to work with dictionaries as test arguments
> GD-341: Using a dictionary parameter in parameterized tests results into a runtime error

- addons/gdUnit3/src/core/GdUnitTools.gd
- addons/gdUnit3/test/mocker/GdUnitMockerTest.gd
- addons/gdUnit3/test/mocker/resources/SceneChanger.gd
- addons/gdUnit3/test/mocker/resources/SceneChanger.tscn
I wanted to mock a SceneTree my `mock(SceneTree)` but it returns null.
Allow to mock on a SceneTree, but still report an error because freeing the mainloop will kill the editor.
> GD-335: Allow to mock `SceneTree`

- addons/gdUnit3/src/core/GdUnitSettings.gd
- addons/gdUnit3/src/ui/parts/InspectorTreeMainPanel.gd
I wan't to not auto collapse all testsuites after success testrun on the inspector
Added a inspector ui option to control the collapse state of a testsuite
> GD-345: Added an option to control the collapse state for a testsuite node on the inspector

- addons/gdUnit3/src/core/GdObjects.gd
- addons/gdUnit3/src/core/GdUnitSettings.gd
- addons/gdUnit3/src/core/_TestCase.gd
- addons/gdUnit3/test/core/GdUnitExecutorTest.gd
- addons/gdUnit3/test/core/ParameterizedTestCaseTest.gd
- addons/gdUnit3/test/core/resources/testsuites/TestSuiteParameterizedTests.resource
Comparing a dictionary with diverent number types was result into a failure.
Godot comparing of dictionarys are type save and needs to be handled customized.
- intoduced a new settings to enable/disable number type save comparision.
- fixed ui bug to add failure report to the right tree item
> GD-347: Allow to compare real vs int typed dictionary

- addons/gdUnit3/src/core/report/GdUnitReport.gd
When execution test in runtime mode (none debug) the failure line is reported as -1 Godot do not get the stacktrace on runtime mode to extract this information
Instead of reporting -1 report `<n/a>` for not available.
> GD-349: Don't report -1 as failure line number at runtime mode

- addons/gdUnit3/src/ui/GdUnitConsole.gd
- addons/gdUnit3/src/ui/parts/RichTextLabelExt.gd
An console error was shown when a tests reports an orphan node.
The error results from RichTextLabel `pop()`, this error occures when more pop's as push's are used
> GD-356: Fix Error on console when tests detects an orphan node

- addons/gdUnit3/src/core/parse/GdScriptParser.gd
- addons/gdUnit3/test/core/GdUnitExecutorTest.gd
- addons/gdUnit3/test/core/ParameterizedTestCaseTest.gd
- addons/gdUnit3/test/core/TestSuiteScannerTest.gd
- addons/gdUnit3/test/core/parse/GdScriptParserTest.gd
- addons/gdUnit3/test/mocker/resources/ClassWithCustomFormattings.gd
Using Strings containing spaces or tabs was failing on parameterized tests. The valus was distorted.
- Fix the test argument parsing by do not clean up the function signature to pare the arguments
- Fix also failing GdUnitExecutor test based on changed gdunit settings during test run
> GD-358: Fix test parameter parsing of parameterized tests with String arguments

- addons/gdUnit3/src/asserts/GdAssertMessages.gd
- addons/gdUnit3/src/asserts/GdUnitAssertImpl.gd
- addons/gdUnit3/src/asserts/GdUnitSignalAssertImpl.gd
- addons/gdUnit3/src/core/GdObjects.gd
- addons/gdUnit3/src/core/GdUnitClassDoubler.gd
- addons/gdUnit3/src/core/GdUnitObjectInteractionsTemplate.gd
- addons/gdUnit3/src/matchers/EqualsArgumentMatcher.gd
- addons/gdUnit3/src/matchers/GdUnitArgumentMatchers.gd
- addons/gdUnit3/src/mocking/GdUnitMockBuilder.gd
- addons/gdUnit3/src/spy/GdUnitSpyBuilder.gd
- addons/gdUnit3/test/mocker/GdUnitMockerTest.gd
- addons/gdUnit3/test/mocker/resources/scenes/TestScene.gd
- addons/gdUnit3/test/spy/GdUnitSpyBuilderTest.gd
- addons/gdUnit3/test/spy/GdUnitSpyTest.gd
- addons/gdUnit3/test/ui/templates/TestSuiteTemplateTest.gd
During fixing #351 i found out a implemented virtual function was never called. The interaction itself was tracked but to original implementation not called.
- Rework on spy to only double implemented virtual functions
- do not call super function on _ready and _input because is do by the engine and will result in double function calls
- cleanup spy builder
- fix failure message typo
- better failure report if the value a instance of `InputEvent`
- fix small bug in signal assert
- improve objects deep equal check
- improve readability of spy/mock tests by reformating expected failure messages
> GD-362: Spy on a implemented virtual function like _input is not working

- addons/gdUnit3/src/ui/GdUnitInspector.gd
On MacOS the `Run Test` was stuck and no execution progress.
Added --path argument to execute the GdUnitRunner scene, it was not need on Windows but needs to be set on MacOS
> GD-357: Fix run test in runtime mode

- addons/gdUnit3/src/core/GdObjects.gd
- addons/gdUnit3/src/core/parse/GdFunctionDescriptor.gd
- addons/gdUnit3/test/core/GdObjectsTest.gd
- addons/gdUnit3/test/core/parse/GdFunctionDescriptorTest.gd
Spy on a function with return type `Variant` was wrong doubled and has return always nothing.
- Check the usage flag of the return descriptor and check for `PROPERTY_USAGE_NIL_IS_VARIANT` to determine it is a `Variant`
- Add missing reflection of Variant type
- Add missing flag `PROPERTY_USAGE_NIL_IS_VARIANT`
> GD-370: Fix spy on function with return type `Varaiant`

- addons/gdUnit3/src/asserts/GdAssertMessages.gd
- addons/gdUnit3/src/spy/GdUnitSpyBuilder.gd
- addons/gdUnit3/src/ui/GdUnitConsole.gd
- addons/gdUnit3/src/ui/parts/RichTextEffectBackground.gd
- addons/gdUnit3/src/ui/parts/RichTextLabelExt.gd
- addons/gdUnit3/test/ui/parts/RichTextEffectBackgroundTest.gd
The failure report has colored diffs but wrong placed
- Fix ident handling on RTL
- rework on background effect for RTL
- fix small error when spy on a node where has no parent
> GD-369: Fix failure report coloring on GdUnit console output

- addons/gdUnit3/src/core/parse/GdScriptParser.gd
- addons/gdUnit3/test/core/parse/GdScriptParserTest.gd
The parser returns wrong arguments when a function acrgument begins with func e.g. `func foo(function_arg :int):`
the argument parsing has been reworked a bit to avoid this error. This is a kind of hotfix, the parsing is fundamentally reimplemented in gdunti4.
> GD-376: Fixes parse error when argument name starts with `func`

- _advanced_testing/fuzzing.md
- _advanced_testing/sceneRunner.md
- index.md
In the section of Fuzzing the examples for was referencig to the wrong function `Fuzzers.random_rangei`
- Corrected the examples to use `Fuzzers.rangei` instead
- Fix also a missmatch on scenerunner#await_signal_on
> GD-379: Update Documentation
